### PR TITLE
filled name and version docs

### PR DESCRIPTION
**Pull request by memsharded**
Hi Chris,

Please check the definitions, thanks!

### CODE REVIEW

**Review by cleeland — COMMENTED** [review]
In the 2nd paragraph for version, can't the source() function get its version from a function/environment variable, too?  If so, I'm not sure why that would make "this approach ... not be valid and fail."

**Comment by memsharded** [comment]
> In the 2nd paragraph for version, can't the source() function get its version from a function/environment variable, too? If so, I'm not sure why that would make "this approach ... not be valid and fail."

No, because when the ``source()`` method runs in a different computer, such environment variable might not be defined at all, or defined for another package, or for a different version, so it will probably fail in most cases.

**Comment by cleeland** [comment]
That doesn't sound like something that's doomed to failure--it sounds more like "caveat emptor".

Rather than saying "this is not valid and fail", I would say something on the order of "making this value not constant means that it may evaluate differently in different contexts (e.g., on different machines or for different users) leading to unrepeatable or unpredictable results.  It should be used with caution."

**Comment by memsharded** [comment]
Good! I have updated the PR with your suggestion, I like it.

**Comment by memsharded** [comment]
Main PR: https://github.com/conan-io/docs/pull/239

**Comment by cleeland** [comment]
Am I supposed to push the "Merge Pull Request" button?  I didn't expect to have permission to do such a thing.  I am happy to do so, however.

**Comment by memsharded** [comment]
Yes, sure! Github permission control is fine :) It is doing a merge over your fork, not over the main conan repo. So, after merge, it will update your current open PR over the main repo.

**Comment by cleeland** [comment]
Ah!  I missed that it was merging to my fork.  Sorry for the confusion.  The deed is done.

**Comment by memsharded** [comment]
Thanks. Merged to main repo now.

**Pull request merged**
